### DISCUSSION TITLE
CI/CD pipelines

### DISCUSSION THREAD

**Discussion by milkshakeuk** [testcontainers/testcontainers-dotnet#537] [Q&A] [answered]
How does this work with Azure DevOps pipelines or GitHub actions? Does it "just work" or is this library only useful in a local developer environment?

Any Azure DevOps and GitHub Actions yml examples would be awesome.

**Comment by HofmeisterAn** [comment, marked as answer]
Testcontainers runs on CI / CD too. All [tests](https://github.com/testcontainers/testcontainers-dotnet/runs/7578138815?check_suite_focus=true#step:7:386) in this library run on [GitHub Actions](https://github.com/testcontainers/testcontainers-dotnet/blob/develop/.github/workflows/cicd.yml) and previous on [Azure DevOps Pipelines](https://github.com/testcontainers/testcontainers-dotnet/blob/f3096c089008a435fccd36536c3a33c7f8e62026/.azuredevops/build.yml). I've used it on Jenkins, GitLab and Bitbucket Pipelines too.

**Comment by marcel-jackow** [comment]
How can I use a private Azure container registry in Azure DevOps pipeline? I'm getting the following error:
```
Docker.DotNet.DockerApiException : Docker API responded with status code=InternalServerError, response={"message":"Head \"https://<my registry>.azurecr.io/v2/<my image>/manifests/latest\": unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information."}
```

I have the following task in Azure DevOps pipeline:
```yaml
- task: AzureCLI@2
  displayName: Test
  inputs:
    azureSubscription: <my service connection with AcrPull role>
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name <my registry>
      dotnet test <my solution>.sln --no-build --configuration Release
```

The tests work locally as my user has access to the Azure container registry

**Reply by marcel-jackow** [reply]
Nevermind, I made it work using the following tasks:
```yaml
- task: Docker@2
  displayName: Docker login
  inputs:
    containerRegistry: <service connection of type Docker Registry>
    command: login

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--no-build --configuration Release'
```

**Reply by HofmeisterAn** [reply]
That's the right approach.

**Comment by intrepid-developer** [comment]
I'm have a similar issue in GitHub Actions when trying to access the GitHub Container Repo.

```yml
name: 'Run Tests'

on:
  workflow_call:
    inputs:
      CSPROJ_PATH:
        required: true
        type: string

permissions:
  packages: read
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Use .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
     
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}     

      - name: 'Run Tests'
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 30
          max_attempts: 2
          retry_wait_seconds: 30
          command: dotnet test ${{ inputs.CSPROJ_PATH }}
```

However when our tests run we still get these errors:

```
Failed to start container
---- Docker.DotNet.DockerApiException : Docker API responded with status code=InternalServerError, response={"message":"denied"}
```
