### DISCUSSION TITLE
Azure Pipeline - Communication TCP between tests and containers with TCP Server

### DISCUSSION THREAD

**Discussion by ghost** [testcontainers/testcontainers-dotnet#679] [Q&A] [answered]
Hi,

Context:
I implemented one test project which created three containers connected with a custom network.
One of the containers has one TCP server listening. The test creates a TCP client that communicates with the container and validates the communication
Locally it works on my computer. In the azure pipeline, it fails.

In the Azure pipeline, three containers and test-containers-ryuk have IP's addresses assigned
Testcontainers-ryuk - 172.19.0.1
Container 1 - 172.19.0.2
Container 2 - 172.19.0.3
Container 3 (TCP server) - 172.19.0.4

Also, when the test checks for TCP server listening (in the test I log the values) , the container doesn't expose TCP port.
In azure, when I check for hostname + GetMappedPublicPort, I get localhost and public port. This is't available in azure.

**The Azure setup is:**

```
pool:  vmImage: ubuntu-latest
container: mcr.microsoft.com/dotnet/sdk:6.0
```
In the container, I execute the task for the test.
```
  - task: DotNetCoreCLI@2
    timeoutInMinutes: 5
    continueOnError: true
    inputs:
      command: 'test'
      projects: $(TEST_FOLDER)/tests/**/*.Tests.Integration.csproj
      arguments: '$(Test_Integration_Args)'
      testRunTitle: 'Run Integration tests'
    displayName: 'Run Integration Tests' 
```

The container configuration with TCP server is the following 
![image](https://user-images.githubusercontent.com/110532753/202432882-8837b27a-26c4-4b3a-870a-7a1bdb7fa21c.png)

From the forums discussions, it seems I'm trying to Run a docker inside docker.
What do I need to configure to expose the TCP Server to the test?
