### ISSUE TITLE
Running .NET integration tests in gitlab CI/CD

### ISSUE THREAD

**Issue by youssefbennour** [testcontainers/testcontainers-dotnet#1279]
### Testcontainers version

3.10.0

### Using the latest Testcontainers version?

Yes

### Host OS

Linux

### Host arch

x86_64

### .NET version

8.0

### Docker version

­ 

### Docker info

­ 

### What happened?

I'm running .NET integration tests with a gitlab-runner (executor: docker).
Integration tests work fine locally, but when run in the pipeline I get this dotnet error, Here's the logs:
```c#
---- System.ArgumentException : Docker is either not running or misconfigured. Please ensure that Docker is running and that the endpoint is properly configured. You can customize your configuration using either the environment variables or the ~/.testcontainers.properties file. For more information, visit:
https://dotnet.testcontainers.org/custom_configuration/ (Parameter 'DockerEndpointAuthConfig')
  Stack Trace:
     at Softylines.Contably.IntegrationTests.Common.TestEngine.IntegrationTestContainers.DisposeAsync() in /builds/comptabilite/comptabilite-back/src/Softylines.Contably.IntegrationTests/Common/TestEngine/IntegrationTestContainers.cs:line 106
----- Inner Stack Trace -----
   at DotNet.Testcontainers.Guard.ThrowIf[TType](ArgumentInfo`1& argument, Func`2 condition, Func`2 ifClause) in /_/src/Testcontainers/Guard.Null.cs:line 62
   at DotNet.Testcontainers.Builders.AbstractBuilder`4.Validate() in /_/src/Testcontainers/Builders/AbstractBuilder`4.cs:line 145
   at DotNet.Testcontainers.Builders.ContainerBuilder`3.Validate() in /_/src/Testcontainers/Builders/ContainerBuilder`3.cs:line 383
   at Testcontainers.PostgreSql.PostgreSqlBuilder.Validate() in /_/src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs:line 101
   at Testcontainers.PostgreSql.PostgreSqlBuilder.Build() in /_/src/Testcontainers.PostgreSql/PostgreSqlBuilder.cs:line 75
```

This is my .gitlab-ci.yml configuration:
```yml
image: mcr.microsoft.com/dotnet/sdk:8.0

variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2

services:
- name: docker:dind
  command: ["--tls=false"]


stages:
  - build
  - test

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --no-restore

integration_tests:
  stage: test
  script:
    - dotnet test
  variables:
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1
  tags:
    - moncef-wise
```

### Additional information

PS: I had seen many discussions about similar problems, I tried some of them, but they didn't work for me.
I've seen some other solutions, but I wasn't able to understand the reasoning behind them, so I needed some more elaboration.

**Comment by HofmeisterAn** [comment]
Please try the following example configuration:

```yml
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
test:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
    - dotnet test
```

**Comment by youssefbennour** [comment]
@HofmeisterAn 
Hi, I got the same error as the above

**Comment by HofmeisterAn** [comment]
> [@HofmeisterAn](https://github.com/HofmeisterAn) Hi, I got the same error as the above

Hm, can you try to run a container manual? Like:

    docker run testcontainers/helloworld

What does:

    docker info
    docker version
    docker context ls

return?

**Comment by youssefbennour** [comment]
@HofmeisterAn Here's what those commands return (keep in mind that I have other contains running already) :
>docker info
docker version
docker context ls
### docker info:
```shell
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.3.3
    Path:     /root/.docker/cli-plugins/docker-compose

Server:
 Containers: 8
  Running: 6
  Paused: 0
  Stopped: 2
 Images: 59
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.8.0-44-generic
 Operating System: Ubuntu 24.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.57GiB
 Name: vps-9de64635
 ID: 86d1dee2-1838-4f7e-8b47-01a540e0136f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### docker version :
```shell
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.22.7
 Git commit:        ce12230
 Built:             Fri Sep 20 11:41:00 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.22.7
  Git commit:       41ca978
  Built:            Fri Sep 20 11:41:00 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc:
  Version:          1.1.14
  GitCommit:        v1.1.14-0-g2c9f560
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker context ls :
```shell
NAME        DESCRIPTION                               DOCKER ENDPOINT               ERROR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock
```

**Comment by HofmeisterAn** [comment]
I would expect the endpoint to be `tcp://docker:2375`, not `unix:///var/run/docker.sock` (`docker context ls`) 🤔. Can you try and comment the `variables` section?

```yml
# variables:
#  DOCKER_HOST: tcp://docker:2375
```

**Comment by youssefbennour** [comment]
@HofmeisterAn 
I did, but nothing has changed, the same error.
Just to make sure we're on the same track, you mean I run it manually on the same machine where the gitlab-runner is running, am I right ? or do you mean to run it in a pipeline and copy the info from logs (idk if there's any difference) ?

> Hm, can you try to run a container manual? Like:
> 
> ```
> docker run testcontainers/helloworld
> ```
> 
> What does:
> 
> ```
> docker info
> docker version
> docker context ls
> ```
> 
> return?

**Comment by HofmeisterAn** [comment]
> or do you mean to run it in a pipeline and copy the info from logs

I meant the pipeline. You need to provide Docker in your pipeline job.

**Comment by youssefbennour** [comment]
My bad, since the gitlab executor is of type 'Docker' then I'll expect 'testcontainers/helloworld' to run inside the dotnet app container, is that right ?

Here's the `gitlab-ci.yml` for testcontainers/helloworld (the default image is `mcr.microsoft.com/dotnet/sdk:8.0`):
```yaml
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
docker_test:
  stage: test
  script:
    - apt-get update && apt-get install -y docker.io
    - docker run testcontainers/helloworld
    - docker info
    - docker version
    - docker context ls
```
And this is the log :
```shell
$ docker run testcontainers/helloworld
docker: error during connect: Post "http://docker:2375/v1.24/containers/create": dial tcp: lookup docker on 213.186.33.99:53: no such host.
See 'docker run --help'.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

This is the log when I comment the `variables` section:
> I would expect the endpoint to be `tcp://docker:2375`, not `unix:///var/run/docker.sock` (`docker context ls`) 🤔. Can you try and comment the `variables` section?

```shell
$ docker run testcontainers/helloworld
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```
Sorry for asking too much, it's my first time setting up a pipeline and luckily I start the journey with testcontainers 😀.
@HofmeisterAn

**Comment by kiview** [comment]
```
docker: error during connect: Post "http://docker:2375/v1.24/containers/create": dial tcp: lookup docker on 213.186.33.99:53: no such host.
```

This strongly suggests an issue with the Docker config within GitLab CI, that is unrelated to Testcontainers. The likely reason is a runner configuration, that does not allow the creation of the Docker service container (e.g. see [this discussion in the GitLab forums](https://forum.gitlab.com/t/error-during-connect-post-http-docker-2375-v1-40-auth-dial-tcp-lookup-docker-on-169-254-169-254-no-such-host/28678)).

We can ignore these logs with commented `DOCKER_HOST, since your desired setup is using a Docker service container, there is no local daemon available under the socket:
```
$ docker run testcontainers/helloworld
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
```

**Comment by youssefbennour** [comment]
@kiview 
@HofmeisterAn 
Cool, that issue is now solved (please read to the end).
I had to add these 2 lines to `config.toml` :
```yml
image = "docker:stable"
privileged = true      
```

and here's the config for `.gitlab-ci.yml` :
```yml
services:
  - name: docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

test:
  image: mcr.microsoft.com/dotnet/sdk:8.0
  stage: test
  script:
    - dotnet test
```

Now I have a connectivity issue with the `Keycloak` container, I'm currently using the published keycloak port in my tests (localhost:{PORT}).

But I assume the test containers are running and exposed inside the dotnet container host, can you figure out the issue ?
