### ISSUE TITLE
[Enhancement]: bitbucket pipeline documentation

### ISSUE THREAD

**Issue by bartengine27** [testcontainers/testcontainers-dotnet#1393]
### Problem

  The documentation to get testcontainers-dotnet up and running in bitbucket seems to be missing. For anyone interested, the following did the job for me.

### Solution

**Example xUnit test code**

```       
     [Fact]
      public async Task Test_HelloWorldContainer()
      {
          //https://github.com/testcontainers/testcontainers-dotnet/issues/492
          TestcontainersSettings.ResourceReaperEnabled = false;
          //Arrange
          
          // Create a new instance of a container.
          var container = new ContainerBuilder()
            // Set the image for the container to "testcontainers/helloworld:1.1.0".
            .WithImage("testcontainers/helloworld:1.1.0")
            // Bind port 8080 of the container to a random port on the host.
            .WithPortBinding(8080, true)
            // Wait until the HTTP endpoint of the container is available.
            .WithWaitStrategy(Wait.ForUnixContainer().UntilHttpRequestIsSucceeded(r => r.ForPort(8080)))
            // Build the container configuration.
            .Build();
          
          await container.StartAsync();

          // Act
          var httpClient = new HttpClient
          {
              BaseAddress = new Uri($"http://{container.Hostname}:{container.GetMappedPublicPort(8080)}")
          };

          var response = await httpClient.GetAsync("/");
          var content = await response.Content.ReadAsStringAsync();

          // Assert
          Assert.True(response.IsSuccessStatusCode, "Expected a successful HTTP response");
          Assert.Contains("Hello world", content, StringComparison.OrdinalIgnoreCase);
      }
```

**Example bitbucket pipeline**

```
image: mcr.microsoft.com/dotnet/sdk:9.0

options:
  docker: true

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - docker
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build --configuration Release
          - dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
        artifacts:
          - test-results.trx
```

### Benefit

Eases Bitbucket usage.

### Alternatives

DinD

### Would you like to help contributing this enhancement?

Yes
