### ISSUE TITLE
Usage of docker-dind in ci pipeline not supported?

### ISSUE THREAD

**Issue by dominikguhr** [testcontainers/testcontainers-dotnet#192]
**Describe the bug**
Hey there. So the question is: is it supported to successfully build a docker-dind image with gitlab and run the testcontainer tests in it? Locally all works fine, but I am struggling with integrating into the ci pipeline right now. Tried to set the DOCKER_HOST and DOCKER_DRIVER as suggested here: https://www.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/ but still having the following errormsg when trying to run the pipeline:
```
System.Net.Http.HttpRequestException : Connection failed
  ----> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Cannot assign requested address /var/run/docker.sock
```
Which as I understand suggests that it does not try to get the remote docker daemon via DOCKER_HOST variable from the pipeline.
I found multiple issues in the gitlab bugtracker, so first I tried to remove the dind service from the specific test step to global, then I tried it with and without setting DOCKER_HOST/DOCKER_DRIVER, but without success right now. 

Any hint is highly appreciated. 
gitlab runner is v12.02.
testcontainers nuget package is 1.1.0
.net core sdk is 3.0

this is an excerpt of the gitlab-ci.yml:

```
unittest-restapi:
  services:
    - docker:19.03-dind
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_DRIVER: overlay2
  image:
    name: mcr.microsoft.com/dotnet/core/sdk:3.0-buster
  stage: unittests
  script:
    - cd restapi
    - dotnet test MyAppTest/MyAppTest.csproj
  only:
    changes:
      - restapi/**/*
```

**To Reproduce**
1. Add testcontainers 1.1.0 to .net core 3 project
2. add gitlab integration from the docs
3. See error when pipeline runs in gitlab-ci ui

**Expected behavior**
Pipeline runs/tests are executed
