### ISSUE TITLE
Docker in docker issue with Gitlab CI. Connection failed.Cannot assign request 

### ISSUE THREAD

**Issue by sudipta-bsci** [testcontainers/testcontainers-dotnet#406]
Hello,
https://github.com/HofmeisterAn/dotnet-testcontainers/issues
I have been struggling to run a MySQL test container on Gitlab CI . Here is my code. 

```
var dockerEndpoint = "tcp://localhost:2375";
            Container = new TestcontainersBuilder<MySqlTestcontainer>()
            .WithImage("mysql:latest")
            .WithDatabase(new MySqlTestcontainerConfiguration()
            {
                Database = MYSQL_DBNAME,
                Username = MYSQL_USER,
                Password = MYSQL_PW
            })
             .WithDockerEndpoint(dockerEndpoint)
            .WithEnvironment("MYSQL_ROOT_HOST", "%")
            .WithEnvironment("MYSQL_ROOT_PASSWORD", MYSQL_PW)
            .WithWaitStrategy(Wait.ForUnixContainer().UntilPortIsAvailable(3306))
            .WithCleanUp(true)
            .Build();
            Container.StartAsync().ConfigureAwait(false).GetAwaiter().GetResult();
```
Here is my Gitlab-ci.yml

```
image: docker:latest

services:
  - name: docker:19.03.0-dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]
    alias: docker

variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - Test

Test:
  stage: Test
  image: mcr.microsoft.com/dotnet/sdk:5.0-buster-slim
  environment:
    name: test
  script:
    - cd src/
    - dotnet restore --disable-parallel
    - dotnet build --no-restore
    -  dotnet test -f net5.0 --logger "console;verbosity=diagnostic"

```

Here is my Gitlab runner configuration

![image](https://user-images.githubusercontent.com/16546336/142674622-4fe19710-ad4c-497d-9834-286ee8a84dd0.png)

Here is error in the pipeline.
![image](https://user-images.githubusercontent.com/16546336/142675207-0ac67a89-51b0-49bd-b279-801ff241b6a1.png)

Any help would be appreciated.
