### ISSUE TITLE
GitLab CI/CD integration

### ISSUE THREAD

**Issue by D4nyi** [testcontainers/testcontainers-dotnet#686]
### Describe the bug
In GitLab CI/CD TestContainers is unable to create the database conatiner for my integration tests.
On Windows it works perfectly fine.

### Errors I got

<details>
  <summary>Error 1.</summary>

```shell
$ docker info
Client:
 Context:    default
 Debug Mode: false
Server:
ERROR: error during connect: Get "http://docker:2375/v1.24/info": dial tcp: lookup docker on <WORKPLACE_DNS>:53: server misbehaving
errors pretty printing info
```
</details>

<details>
  <summary>Error 2.</summary>

```shell
Failed <TEST_METHOD> [1 ms]
Error Message:
  DotNet.Testcontainers.Containers.ResourceReaperException : Initialization has been cancelled.
Stack Trace:
    at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
  at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartNewAsync(Guid sessionId, IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, String ryukImage, TimeSpan initTimeout, CancellationToken ct)
  at DotNet.Testcontainers.Containers.ResourceReaper.GetAndStartDefaultAsync(IDockerEndpointAuthenticationConfiguration dockerEndpointAuthConfig, CancellationToken ct)
  at DotNet.Testcontainers.Clients.TestcontainersClient.RunAsync(ITestcontainersConfiguration configuration, CancellationToken ct)
  at DotNet.Testcontainers.Containers.TestcontainersContainer.Create(CancellationToken ct)
  at DotNet.Testcontainers.Containers.TestcontainersContainer.StartAsync(CancellationToken ct)
  at <CUSTOM_API_FACTORY>.InitializeAsync() in <path/to/CUSTOM_API_FACTORY.cs>:line 98
```
```csharp
public async Task InitializeAsync()
{
    await _db.StartAsync(); // <- line 98
   // ...
}
```
</details>

### Environment

<details>
  <summary>GitLab CE (self-managed)</summary>

- v15.5.4 (always kept up-to-date), runs in docker
- Ubuntu Server 20.04.5 LTS (GNU/Linux 5.4.0-132-generic x86_64)
- Docker version 20.10.21, build baeda1f
</details>

<details>
  <summary>GitLab Shared Runner (always kept up-to-date)</summary>

```shell
Version:      15.6.0
Git revision: 44a1c2be
Git branch:   15-6-stable
GO version:   go1.18.8
Built:        2022-11-21T23:40:12+0000
OS/Arch:      linux/amd64
```
</details>

<details>
  <summary>GitLab Runner Toml</summary>

```toml
concurrent = 2
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "default"
  url = "URL"
  id = 7
  token = "TOKEN"
  token_obtained_at = 2018-01-01T00:00:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/mnt/hdd/runner/cache:/cache", "/mnt/hdd/runner/build:/build", "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
    allowed_pull_policies = ["always", "if-not-present", "never"]
    pull_policy = ["if-not-present", "always", "always"]
```
</details>

<details>
  <summary>.gitlab-ci.yml</summary>

```yml
stages:
    - install
    - test

variables:
    # Instruct Testcontainers to use the daemon of DinD, use port 2735 for non-tls connections.
    #DOCKER_HOST: "host.docker.internal"
    # Instruct Docker not to start over TLS.
    #DOCKER_TLS_CERTDIR: ""
    # Improve performance with overlayfs.
    #DOCKER_DRIVER: overlay2
    OBJECTS_DIRECTORY: "obj"
    NUGET_PACKAGES_DIRECTORY: ".nuget"
    NUGET_CONFIG_FILE: "nuget.config"
    SOURCE_CODE_PATH: "src"
    TEST_PROJ_PATH: "test"
    DOTNET_SDK_IMAGE: "mcr.microsoft.com/dotnet/sdk:7.0-jammy"
    PUBLISH_PROFILE: "$SOURCE_CODE_PATH/Server/Properties/PublishProfiles/Linux.pubxml"
    BUILD_PROJECT: "$SOURCE_CODE_PATH/Server/Server.csproj"
    RELEASE_ARTIFACTS: "$SOURCE_CODE_PATH/bin/Release"

default:
    image:
        name: "$DOTNET_SDK_IMAGE"
        pull_policy: if-not-present
    # DinD service is required for Testcontainers
#    services:
#        - name: docker:dind
#          # explicitly disable tls to avoid docker startup interruption
#          command: ["--tls=false"]
#    before_script:
#        - "docker info"
    cache:
        key: "nuget-cache"
        paths:
            - "$SOURCE_CODE_PATH/*/$OBJECTS_DIRECTORY/*.json"
            - "$SOURCE_CODE_PATH/*/$OBJECTS_DIRECTORY/project.nuget.cache"
            - "$TEST_PROJ_PATH/*/$OBJECTS_DIRECTORY/*.json"
            - "$TEST_PROJ_PATH/*/$OBJECTS_DIRECTORY/project.nuget.cache"
            - "$SOURCE_CODE_PATH/*/$OBJECTS_DIRECTORY/*.csproj.nuget.*"
            - "$TEST_PROJ_PATH/*/$OBJECTS_DIRECTORY/*.csproj.nuget.*"
            - "$NUGET_PACKAGES_DIRECTORY"
            - "$RELEASE_ARTIFACTS"
        policy: pull-push

install:
    stage: install
    script:
        - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY --configfile $NUGET_CONFIG_FILE
    # only:
    #     changes:
    #         - "**/*.csproj"

test:
    stage: test
    before_script:
        - apt update -qq && apt -y -qq upgrade && apt install -y -qq --no-install-recommends curl gnupg
        - mkdir -p /etc/apt/keyrings && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        - echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" > /etc/apt/sources.list.d/docker.list
        - apt update -qq && apt -y -qq install --no-install-recommends docker-ce-cli
        - docker ps
    script:
        - dotnet test --no-restore
```
</details>

### Additional context
- The 'Error 1.' came when I used the DinD configuration (it is commented out in the .yml config)
- The 'Error 2.' is thrown when I use the currnet configuration
- If I understand correctly TestContainers is using the Docker REST API to communicate with the Docker daemon and in my case to create sibling containers.
- As the integration tests are starting the "watchdog" (`testcontainers-ryuk-<GUID>`) container is spun up, but the database (`postgres:alpine`) should also be created but is not.
- And it fails with a timeout 😢
